### ISSUE TITLE
index.js:155 Uncaught Error: Cannot find module './typeTrie'

### ISSUE THREAD

**Issue by linonetwo** [orisano/graphemesplit#6]
@IvanSanchez Hi, how did you solve this before?

**Comment by linonetwo** [comment]
Can you use `preval.macro` to load it on build time? @orisano 

As I did in https://github.com/linonetwo/segmentit/blob/ed33faa10f928ec5f9e698b6af9afb54d45e7d7d/src/knowledge/index.js#L2-L11

**Comment by IvanSanchez** [comment]
> @IvanSanchez Hi, how did you solve this before?

I cannot recall. I'm not very familiar with how this project undergoes bundling.

**Comment by linonetwo** [comment]
Solving `require` problem in a web project is not easy, can you make it easier on your side? @IvanSanchez
