### ISSUE TITLE
Make graphemesplit compatible with React Native

### ISSUE THREAD

**Issue by zencephalon** [orisano/graphemesplit#9]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `graphemesplit@2.4.2` for the project I'm working on.

On React Native I got this error: Buffer undefined

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/graphemesplit/index.js b/node_modules/graphemesplit/index.js
index e5c7827..6f5652c 100644
--- a/node_modules/graphemesplit/index.js
+++ b/node_modules/graphemesplit/index.js
@@ -1,6 +1,7 @@
 const types = require("./types");
 const typeTrieData = require("./typeTrie.json").data;
 const extPictData = require("./extPict.json").data;
+global.Buffer = global.Buffer || require("buffer").Buffer;
 
 const UnicodeTrie = require("unicode-trie");
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by orisano** [comment]
Thanks for the reporting!
Can you make a pull request?
Contributions are welcome.

**Comment by orisano** [comment]
Maybe it fixed by https://github.com/orisano/graphemesplit/commit/277ddab0a4976cbb55cbe401527b6dca1c09253b
I released a new version. please use v2.4.3!

**Comment by zencephalon** [comment]
Yes, that does it, thanks!
